export const SAVE_CHECKBOX_STATUS_ACTION = "PROFILE::SAVE_CHECKBOX_STATUS_ACTION";
export const CHANGE_USER_NAME_ACTION = "PROFILE::CHANGE_USER_NAME_ACTION";
export const TOGGLE_USER_NAME_ACTION = "PROFILE::TOGGLE_USER_NAME_ACTION";